### ISSUE TITLE
Phosphor_v1_8.jar File exception

### ISSUE THREAD

**Issue by Clemintina** [Youded-byte/lunar-client-qt#3]
The launcher won't launch due to a file called "Phosphor_v1_8.jar" doesn't exist or can't be found in the directory.

Full stacktrace:

```
Exception in thread "main" java.nio.file.NoSuchFileException: .\Phosphor_v1_8.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:284)
	at com.moonsworth.lunar.ichor.OIOORRORCRHOOCICORRCHOHRC.OIOORRORCRHOOCICORRCHOHRC.RHOIOCRHOCHOOHHCOHIOIIRHI(Unknown Source)
	at com.moonsworth.lunar.ichor.ORRCHORCCOOOCCORCIHCROOCC.RHOIOCRHOCHOOHHCOHIOIIRHI(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.moonsworth.lunar.ichor.ORRCHORCCOOOCCORCIHCROOCC.<init>(Unknown Source)
	at com.moonsworth.lunar.ichor.ORRCHORCCOOOCCORCIHCROOCC.<init>(Unknown Source)
	at com.moonsworth.lunar.ichor.ORRCHORCCOOOCCORCIHCROOCC.<init>(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
```

**Comment by Clemintina** [comment]
The fix to clear the ``%userprofile%\.lunarclient\offline\multiver`` directory
